### ISSUE TITLE
Add support for pop-out windows

### ISSUE THREAD

**Issue by zkamvar** [crsh/citr#15]
Currently I'm unable to use citr with Rmd documents in pop-out windows with RStudio 1.1.342. I don't know if there is a way to address this, but I just thought I would bring it to your attention. 

Besides that, citr is really helpful for my workflow. Thanks!

**Comment by crsh** [comment]
Good point. I haven't been able to make this work with the current version of `rstudioapi`. But I would really like citr to be able to do this, so I'll keep at it and let you know as soon as I find a way.

**Comment by crsh** [comment]
It [appears](https://github.com/rstudio/rstudioapi/issues/55) we will have to wait for the next RStudio release before I can address this issue.

**Comment by zkamvar** [comment]
Thank you for looking into this! I update RStudio daily, so I'll post back in a few days if it becomes fixed with RStudio updates. 😃

**Comment by crsh** [comment]
Have you had a chance to try this out with the latest preview release? I'm asking because I may still have to make some adjustments to the addin after the IDE update.

**Comment by zkamvar** [comment]
Yes. I tried it today with the same results (screenshot gif attached).

I'm using the daily Rstudio version 1.1.358

![citr](https://user-images.githubusercontent.com/3639446/30125157-21086df4-92fd-11e7-9afe-d84f682dad42.gif)

**Comment by zkamvar** [comment]
Note: I'm using a keyboard shortcut to access the addin

**Comment by zkamvar** [comment]
Wait.... It appears to work now when there are other tabs open?

**Comment by crsh** [comment]
This should be fixed by my last commit. Try installing from this GitHub repository and let me know if it works for you.

**Comment by zkamvar** [comment]
Everything is working now! Thank you 👍

**Comment by solarchemist** [comment]
I'm sorry to comment on a closed issue, but this is *not* working in RStudio *Server* 1.1.456.

Citr works as expected with the source window in-place, but cannot place the citation inside the source document with the source pane in detached mode. The citation is written to the console instead, just like @zkamvar shows in the gif.

I have not configured any keyboard shortcut, and running Rstudio Server in Chromium 72.0.3626.122 (Developer Build) on Debian 9.8.
