### ISSUE TITLE
The name list field author cannot be parsed

### ISSUE THREAD

**Issue by quantitative-technologies** [crsh/citr#18]
was caused by the following bibtex entry:

@article{10.1371/journal.pone.0109458,
    author = {Liu, Yang-Yu AND Nacher, Jose C. AND Ochiai, Tomoshiro AND Martino, Mauro AND Altshuler, Yaniv},
    journal = {PLOS ONE},
    publisher = {Public Library of Science},
    title = {Prospect Theory for Online Financial Trading},
    year = {2014},
    month = {10},
    volume = {9},
    url = {https://doi.org/10.1371/journal.pone.0109458},
    pages = {1-7},
    abstract = {Prospect theory is widely viewed as the best available descriptive model of how people evaluate risk in experimental settings. According to prospect theory, people are typically risk-averse with respect to gains and risk-seeking with respect to losses, known as the “reflection effect”. People are much more sensitive to losses than to gains of the same magnitude, a phenomenon called “loss aversion”. Despite of the fact that prospect theory has been well developed in behavioral economics at the theoretical level, there exist very few large-scale empirical studies and most of the previous studies have been undertaken with micro-panel data. Here we analyze over 28.5 million trades made by 81.3 thousand traders of an online financial trading community over 28 months, aiming to explore the large-scale empirical aspect of prospect theory. By analyzing and comparing the behavior of winning and losing trades and traders, we find clear evidence of the reflection effect and the loss aversion phenomenon, which are essential in prospect theory. This work hence demonstrates an unprecedented large-scale empirical evidence of prospect theory, which has immediate implication in financial trading, e.g., developing new trading strategies by minimizing the impact of the reflection effect and the loss aversion phenomenon. Moreover, we introduce three novel behavioral metrics to differentiate winning and losing traders based on their historical trading behavior. This offers us potential opportunities to augment online social trading where traders are allowed to watch and follow the trading activities of others, by predicting potential winners based on their historical trading behavior.},
    number = {10},
    doi = {10.1371/journal.pone.0109458}
}

**Comment by crsh** [comment]
Hi, thanks for reaching out. Some testing shows that the problem is caused by the `AND`s. If you replace them with `and`s the file is parsed as expected. This error is due to the `read.bib()` function from the `bibtex` package. I've reported the error there.

**Comment by statzhero** [comment]
I assume there's no solution since this issue was reported?

**Comment by crsh** [comment]
I think [there is](https://github.com/ropensci/bibtex/commit/01a77a6b58da8b6e1ba75539fdd9c239fbf26dfd), but the fix has not made it to CRAN. Have you tried installing `bibtex` from the GitHub repository?

**Comment by statzhero** [comment]
I added a comment there to describe my issue.
