### ISSUE TITLE
.bib-file(s) not found when full path specified in YAML header

### ISSUE THREAD

**Issue by kstierhoff** [crsh/citr#26]
Hi,
citr is not reading the .bib file when the full path is specified in the YAML header ("D:/TEST/citr_test/bib/library.bib").  

![image](https://user-images.githubusercontent.com/2256746/35295387-e2b96f6e-002d-11e8-95a0-08b99e15db0f.png)

I realized that it was working fine when I specified a relative path (e.g., bib/library.bib).

Any idea why I'm getting this behavior? 

Thanks,
Kevin

**Comment by crsh** [comment]
Hi Kevin, could you verify that the path is specified correctly? The screenshot suggests that `citr` read the path `D:/library.bib` from the YAML header. Also, what version `citr` are you currently using?

**Comment by kstierhoff** [comment]
Sorry, that was the wrong grab. I have updated the screen shot in the original post. Thanks for the quick reply.  I am using v 0.2.0.9055.

**Comment by kstierhoff** [comment]
Hi, I just updated the thread to correct the screen grab and also provide
the version. Sorry for the omission.

**Comment by crsh** [comment]
Thanks, for the report. I just pushed a commit that should fix the issue. Feel free to open if this doesn't work.
