### ISSUE TITLE
Using citr leaves warning message: readLines(parents_path[parents])

### ISSUE THREAD

**Issue by koliajaykr** [crsh/citr#27]
Hi @crsh ,

This is not a very urgent issue. And I'm sure it is just because of some issue with my R project files. Because this warning is not coming in my other R projects.

R output is running good. But somehow citr is leaving a warning message like this:

`Listening on http://127.0.0.1:5358 Warning message: In readLines(parents_path[parents]) : incomplete final line found on '/home/ajay/PhD_Thesis_AJAY/index.Rmd`

I hope that this warning will not create any issue in future.

a helpful `warning` screen-shot:
![screenshot from 2018-02-01 23-41-04](https://user-images.githubusercontent.com/28312545/35714610-cd58d196-07f3-11e8-8ce3-ff0d257f4ff2.png)

**Comment by retorquere** [comment]
If BBT can do something to fix this I'd be happy to, but I'd need to know what `citr` is calling when the error happens, what it gets, and what it expects.

**Comment by crsh** [comment]
Hi @koliii, the error message points out that your `index.Rmd` is missing an EOL. Try adding an newline to the end of the document to see if that resolves the issue. If it does, I think there is an easy fix for this.

**Comment by koliajaykr** [comment]
Hello @crsh ,  thanks your suggestion for the `index.Rmd` file worked perfectly. :)

**Comment by crsh** [comment]
Great. After thinking some more about this I'm hesitant to disable warnings for `readLines()` because if there are embedded nuls it may lead to incomplete reading of the files. Hence, I will not "fix" this issue for now.
