### ISSUE TITLE
Inconsistent error when using citr with Zotero

### ISSUE THREAD

**Issue by chriscastille6** [crsh/citr#29]
When I attempt to load a library, I get the following message:

Warning in do_read_bib(file, encoding = .Encoding, srcfile) :
  
8e1COZH0yPnDdpDyz3zpK6kKzqwx3pio.bib:2:0
	syntax error, unexpected $end
	Dropping the entry `CascioInvestingPeopleFinancial2008` (starting at line 28) 
Warning: Error in do_read_bib: unprotect_ptr: pointer not found
Stack trace (innermost first):
    105: do_read_bib
    104: RefManageR::ReadBib
    103: import_bbt
    102: load_betterbiblatex_bib
    101: eval
    100: eval
     99: shiny::withProgress
     98: <reactive>
     87: bibliography
     86: force
     85: need
     84: lapply
     83: sapply
     82: validate
     81: renderText
     80: func
     79: origRenderFunc
     78: output$read_error
      3: shiny::runApp
      2: runGadget
      1: citr:::insert_citation
Warning: Error in do_read_bib: unprotect_ptr: pointer not found
Stack trace (innermost first):
    91: <Anonymous>
    90: stop
    89: bibliography
    88: tag
    87: tags$a
    86: actionLink
    85: tag
    84: tags$span
    83: span
    82: helpText
    81: renderUI
    80: func
    79: origRenderFunc
    78: output$zotero_status
     3: shiny::runApp
     2: runGadget
     1: citr:::insert_citation
Warning: Error in do_read_bib: unprotect_ptr: pointer not found
Stack trace (innermost first):
    61: <Anonymous>
    60: stop
    59: bibliography
    58: observerFunc
     3: shiny::runApp
     2: runGadget
     1: citr:::insert_citation
ERROR: [on_request_read] connection reset by peer

Please advise.

**Comment by crsh** [comment]
Hi Christopher, judging from the error message it seems you are trying to import references from you Zotero bibliography, is that correct? Are you using the current development version of `citr` available from this repository (`devtools::install_github("crsh/citr")`) or the CRAN version? If the latter is the case, try updating to see if the error persists. If it does, please provide the `.bib` file for your Zotero bibliography available at `http://localhost:23119/better-bibtex/library?library.bibtex` when Zotero is running.

**Comment by chriscastille6** [comment]
Hi there. I'm trying to import references from my Zotero library. I followed your advice and downloaded the developer version. Unfortunately the following error is still persisting. 
"Warning: Error in do_read_bib: unprotect_ptr: pointer not found"

Please advise.

**Comment by crsh** [comment]
I need to see the bibliography file you are trying to import. Please provide the .bib file for your Zotero bibliography available at http://localhost:23119/better-bibtex/library?library.bibtex when Zotero is running.

**Comment by chriscastille6** [comment]
Happy to, but the file simply has:

translation failed

Written in it. 

If you like, I could invite you to my Zotero library. Would that help?

**Comment by chriscastille6** [comment]
Note: this happens for both my personal and online library.

**Comment by chriscastille6** [comment]
[Bibfile.txt](https://github.com/crsh/citr/files/2109018/Bibfile.txt)

I'm sorry – I just realized what you were asking for. Please see the attached bibfile, which I've uploaded as a .txt file. Hopefully, this doesn't cause a problem.

I should note that this file does not appear to have the files from my group/shared Zotero library in it, which is the library that I'd like to draw upon when using citr. 

Thanks in advance for your help in diagnosing the problem.

**Comment by crsh** [comment]
I'm not sure what's going on here, but it is certainly not a `citr`-problem. The exported `.bib`-file is faulty. All braces and newlines are escaped with `\` and there is some additional stuff at the top of the file that should not be there:

~~~
{\rtf1\ansi\ansicpg1252\cocoartf1561\cocoasubrtf400
{\fonttbl\f0\fmodern\fcharset0 Courier;}
{\colortbl;\red255\green255\blue255;\red0\green0\blue0;}
{\*\expandedcolortbl;;\cssrgb\c0\c0\c0;}
\margl1440\margr1440\vieww10800\viewh8400\viewkind0
\deftab720
\pard\pardeftab720\partightenfactor0

\f0\fs26 \cf0 \expnd0\expndtw0\kerning0
~~~

If this file was generated by Better Bib(La)TeX you may want to check your settings or reach out to the developer at [their GitHub repository](https://github.com/retorquere/zotero-better-bibtex).

> I should note that this file does not appear to have the files from my group/shared Zotero library in it, which is the library that I'd like to draw upon when using citr.

This is currently not possible with the version available from CRAN, but if you install `citr` from this repository you will be able to access all shared and group libraries.

**Comment by chriscastille6** [comment]
Ok – thanks for the advice. It does seem to be working now, but I have not yet taken the advice you gave, which is weird. 

Basically, when I restarted my Zotero session, everything worked.
