### ISSUE TITLE
Unicode char α (U+3B1) error

### ISSUE THREAD

**Issue by andreifoldes** [crsh/citr#30]
Hello

When I try to cite this article: https://www.ncbi.nlm.nih.gov/pubmed/28069918
I get the following error msg:

! Package inputenc Error: Unicode char α (U+3B1)
(inputenc)                not set up for use with LaTeX.

cheers

**Comment by crsh** [comment]
Hi Andrei, are you taking the bibliographic information from a `.bib` file (if so, could you provide the Bib(La)TeX code?) or from Zotero (if so, could you try to provide the Bib(La)TeX code generated by BetterBib(La)Tex available at `http://localhost:23119/better-bibtex/library?library.bibtex`?)?

**Comment by andreifoldes** [comment]
Hi its from Zotero:
here is my export
[bibitex.txt](https://github.com/crsh/citr/files/1904285/bibitex.txt)

interestingly here the greek letter alpha is spelled out alpha

**Comment by crsh** [comment]
Okay, that's interesting. It's hardly surprising then that I can read this file. Could you do me a favor and try if the greek letter is exported as is if you use access the bibliography via `http://localhost:23119/better-bibtex/library?/1/library.bibtex`?

**Comment by crsh** [comment]
Ah, sorry. Maybe I missunderstand. Are you experiencing this error when you try to insert the citation or when you try to knit the document? If the latter is the case, this is unrelated to `citr` and you may want to either try to change the title of the article to use nonunicode characters (and report this with the author of the [BetterBib(La)TeX Zotero extension](https://github.com/retorquere/zotero-better-bibtex)) or use a different [LaTeX engine](https://rmarkdown.rstudio.com/pdf_document_format.html#latex_engine), e.g., XeLaTeX.

**Comment by andreifoldes** [comment]
Indeed sorry it appears during the Knitting but I thought best to suspect Citr as a fist element in the process.

**Comment by crsh** [comment]
No problem. I think this issue could be interesting for the BetterBib(La)TeX project as it may be a problem with automatic unicode conversion (paging @retorquere).
