### ISSUE TITLE
YAML front matter missing or no bibliography file(s) specified.

### ISSUE THREAD

**Issue by Gnossos** [crsh/citr#31]
The attached zip file, Archive.zip,
[Archive.zip](https://github.com/crsh/citr/files/1989611/Archive.zip)
 contains two files, Project_Notebook.Rmd and references.bib reside in the same directory. Yet citr gives me an error message, "YAML front matter missing or no bibliography file(s) specified."

Earlier I had 3 bibliographic entries in references.bib but was getting errors. So I removed them from the Zotero collection that generates the bib file. But even with only one item, citr has trouble.

**Comment by crsh** [comment]
Hi @Gnossos, I cannot reproduce your problem. I downloaded and unzipped the folder, opened the Rmd and called the addin. It works as expected. From what you are describing the problem doesn't seem to be related to your Zotero collection. Could you try if updating the package or using the development version (`devtools::install_github("crsh/citr")`) resolves the issue? If it doesn't could you provide the output returned by `devtools::session_info()`?
