### ISSUE TITLE
Error in do_read_bib: String too long for 131072-character buffer

### ISSUE THREAD

**Issue by heinonmatti** [crsh/citr#33]
I get this warning: `Error in do_read_bib: String too long for 131072-character buffer`, after interrupting the process when I have opened the insert citation box and the box is in the middle of "Loading bibliography..."

The file from http://localhost:23119/better-bibtex/library?/1/library.bibtex is enclosed (with the extension changed to .txt).

Any thoughts?

[library.bibtex.txt](https://github.com/crsh/citr/files/2154919/library.bibtex.txt)

**Comment by crsh** [comment]
Hmm, I seem to be able to read this file without a problem. This may be related to you version of the `bibtex` or `RefManegeR` package. Could you try installing `citr` from this repository and see if that resolves the problem?

**Comment by crsh** [comment]
If it does not, could you try and confirm that the error persists when you use the addin to read this file (rather than your Zotero bibliography directly)? To do so you need to either close Zotero or click the `Disconnect`-action link and specify the path to the `.bib` file.

**Comment by heinonmatti** [comment]
Installed `citr` from the github repo and it works again! 

It did work for a while earlier, too, before starting to throw in that error. But now has worked for a decent while; will close issue and reopen if the thing reappears. Many thanks!
