### ISSUE TITLE
Changing References Format

### ISSUE THREAD

**Issue by alapo** [crsh/citr#34]
I do apologize for the introductory nature of this question. I installed that package once I saw its potential. I'm curious if anyone would know how to change the default reference format (shown below)

To another format such as IEEE. I prefer using something with numbers (similar to Wikipedia) when I'm writing because it takes up less space. 

![image](https://user-images.githubusercontent.com/33550946/42440355-883d03b4-8333-11e8-8050-a8ae87485aed.png)

I'm using connected via Zotero.

**Comment by crsh** [comment]
Hi! The format of the citations and references is controlled by the CSL file used by the R Markdown template. See the [online documentation](https://rmarkdown.rstudio.com/authoring_bibliographies_and_citations.html#citation_styles) for details.

**Comment by alapo** [comment]
Thank you very much for such a quick and kind response. For anyone interested you can download a list of csl files [here](https://github.com/citation-style-language/styles)
