### ISSUE TITLE
Load database silently

### ISSUE THREAD

**Issue by Robinlovelace** [crsh/citr#36]
Here's an idea related to https://github.com/crsh/citr/issues/23 : instead of loading the database in the shiny app (which freezes the entire RStudio session) could you not make that part of it happen in silent, either in the current R session (with a loading bar?) before launching the app, or in a new process created by the `future` pkg or similar on the first time the link is made?

**Comment by crsh** [comment]
Yes, that's definitely a good idea. I'm currently a little overwhelmed with other projects, but improving the speed of the Zotero connection is high up on my priority list for this package.

One thing I'm wondering about: In the development version it's possible to access shared group libraries in addition to the personal Zotero library. It may not always be desirable to import all libraries (and in my use case this can take a long time). The addin therefore allows users to specify which libraries to load. If the Zotero database is loaded before the addin is executed it would have to import all libraries. If this happens in a separate session, I guess that may be feasible. In addition the libraries could be stored separately and merged and accessed only if specified in the addin. However, I'm not sure how to handle the situation when the libraries are still being imported when the addin is called. Any suggestions?

**Comment by Robinlovelace** [comment]
I see your points re capacity (know the feeling!) and libraries. However I think that loading all citations is a good default: think of the person starting a project. It's most useful to have access to all available citations when you're doing a search. The 'silent load' option wouldn't actually need to make it any faster, would just delay the launch of the app, allowing the user to continue writing prose while the R session does its business before launching into shiny. `Please wait, loading DB` would be useful too.

**Comment by crsh** [comment]
Ah, I see what you are suggesting. That makes sense. I'll look into it. Thanks!

**Comment by crsh** [comment]
Closing in favor of #55

**Comment by Robinlovelace** [comment]
Agreed, sorry for duplicating my own issue!
