### ISSUE TITLE
Focus 

### ISSUE THREAD

**Issue by carbonmetrics** [crsh/citr#40]
First, thanks for making this add-in available! 
Feature request: 
When you hit the shortcut you will _always_ want to have the focus on "Search terms". 
This is however not the default behaviour, you will have to click on the search box first. 
That is unnecessary and is costing a lot of time in the course of writing an article or thesis. 
So it would be great if the focus would be on the search box when hitting the shortcut key.

**Comment by crsh** [comment]
Great suggestion. Any pointers on how to do this? I've tried to find a solution for this but have come up empty so far.

**Comment by carbonmetrics** [comment]
Er...no idea either.

**Comment by crsh** [comment]
Note to self: I've spent some time on this and it turns out to be tricky because the async execution of JavaScript calls. When I focus the input field, the focus is lost right away whenever `updateSelectizeInput()` is run. Not sure how to address this.

**Comment by crsh** [comment]
I think I've got it working. If you find the time to try it out, let me know if it works for you.
