### ISSUE TITLE
slow import/reload of Zotero library

### ISSUE THREAD

**Issue by ukuvainik** [crsh/citr#64]
Thank you for developing such promising software!
My issue is that loading Zotero from citr takes ~2 minutes, also when reupdating.

A typical use case is that I am writing in Rmarkdown. I then realise i need to cite a paper not in my library. I add a paper Zotero via browser. To see that paper in citr, I need to reconnect the Zotero library, which means 2 minutes of waiting to use R.

My library is ~4100 items.

BBT was kind enough to debug the usage on their end, and it seems that BBT handles it in 6 seconds. What could I do to improve the time from citr side?

https://github.com/retorquere/zotero-better-bibtex/issues/1391#issuecomment-582449729

citr 0.3.2
Rstudio 1.2.1578
R version 3.6.2
Platform: x86_64-pc-linux-gnu (64-bit)

**Comment by retorquere** [comment]
If it's parsing the returned bibtex is what takes long, citr could request both the CSL and the bib version of the library; CSL should be pretty easy to parse.

**Comment by jrennstich** [comment]
I think this might be connected to https://github.com/crsh/citr/issues/58.

**Comment by crsh** [comment]
Thanks for reporting. Closing in favor of #58.
