### ISSUE TITLE
Search for bibliography paths in index.Rmd

### ISSUE THREAD

**Issue by yihui** [crsh/citr#7]
In `insert_citation()`, it will be great if you can also search for bib paths in index.Rmd if it exists. This can be useful for packages that take multiple Rmd files as input, e.g. bookdown (https://github.com/rstudio/bookdown/).

**Comment by crsh** [comment]
Thanks for the suggestion!

I think I'll add a new option `citr.parent_documents` that contains the names of candidate R Markdown files to search for references (e.g., I personally often use a `master.Rmd`). By default, I would set the option to `c("index.Rmd", "master.Rmd")`. These files should probably only be used if the current document does not include a YAML front matter.

Would that work for your purposes?

**Comment by yihui** [comment]
Yes that will work, but I'd like it to be as automated as possible. When `_bookdown.yml` or `_site.yml` is present, we are almost sure that the bib paths are in index.Rmd. Users will love "It Just Works ™️" :)

**Comment by crsh** [comment]
I implemented the discussed changes in my last commit. Additionally, I enforced, that, even if `index.Rmd` is not included in the option `citr.parent_documents`, if either `_bookdown.yml` or `_site.yml` exist at the location of the current document `index.Rmd` will be searched for bibliographies.

Let me know what you think. There is one other change I want to make, but if this solution works for your purposes I would try to submit an update of the package to CRAN soon.

**Comment by yihui** [comment]
Thanks, but it does not seem to work well. You can use this repo as an example: https://github.com/rstudio/bookdown-demo If I open any Rmd other than index.Rmd from a fresh R session, and insert citations, I don't see the correct bib files read from index.Rmd:

![screen shot 2016-09-02 at 11 33 03 pm](https://cloud.githubusercontent.com/assets/163582/18222731/a611d73e-7165-11e6-8c41-7323725d8137.png)

However, if I click the addin again, the bib files are found.

![screen shot 2016-09-02 at 11 35 24 pm](https://cloud.githubusercontent.com/assets/163582/18222746/f4a71f58-7165-11e6-826a-deefb700ab6a.png)

**Comment by crsh** [comment]
Thanks for testing this. It seemed to work well for me, but I'll take a closer look.

**Comment by crsh** [comment]
So, I have difficulty reproducing the problem on my machine, but I have now updated the addin to access the source editor context instead of active document (if the installed version of RStudio is up to date). Is it possible your cursor was in the console rather than inside the Rmd?

**Comment by yihui** [comment]
That might be the reason. Just tested the current version, and it seems to be working now. Thanks a lot!
