### ISSUE TITLE
Handling missing fields in bibtex

### ISSUE THREAD

**Issue by awmercer** [crsh/citr#8]
Currently, citr ignores bibtex entries that are missing certain fields when it loads the library in memory (e.g. if year is missing from a journal article). Citation management programs such as Mendeley or Zotero allow for missing fields. Bibtex itself will allow missing fields and simply omit them from the final rendered citation. Would it be possible to allow citr to allow missing fields, either by ignoring them or converting them to "missing" or an empty string?

**Comment by crsh** [comment]
This seems like a reasonable request and easy to do. Thanks for the feedback. ;)
