### ISSUE TITLE
Allow bibtype "Document" to be read by citr

### ISSUE THREAD

**Issue by goergen95** [crsh/citr#82]
Thanks for the great work. It is a really useful package! I have some difficulties citing datasets though. When I use Zotero to automatically read in a dataset based on the DOI it gets the item type `Document` from Zotero.
When I am loading my library with citr in my R session I am getting the message:

```
Ignoring entry '<BibTex key>'  (line1851) because:
	‘bibtype’ has to be one of Article, Book, MVBook, InBook, BookInBook, SuppBook, Booklet, Collection, MVCollection, InCollection, SuppCollection, Manual, Misc, Online, Patent, Periodical, SuppPeriodical, Proceedings, MVProceedings, InProceedings, Reference, MVReference, InReference, Report, Set, Thesis, Unpublished, XData, Customa, Customb, Customc, Customd, Custome, Customf, Conference, Electronic, MastersThesis, PhdThesis, TechReport, Www, Artwork, Audio, BibNote, Commentary, Image, Jurisdiction, Legislation, Legal, Letter, Movie, Music, Performance, Review, Software, Standard, Video
```
I then have to manually change the item type to something that citr will accept. Sometimes this can also lead to loss of information in the citation, e.g. when the publisher field gets deleted if I change the type to `Journal Article` for example.

I wonder if this issue is on the side of citr. If it is I would argue that the item type `Document` should be supported. Maybe I am missing something and I can easily use one of the existing types. However, since Zotero will read in such datasets as "Document" this would at least require manually changing the type before loading the library with citr.

**Comment by crsh** [comment]
Hi Darius, have you tried switching to BibLaTeX in the settings of the addin? I don't think `@document` is a valid BibTeX entry type.

**Comment by goergen95** [comment]
Hi! 
Thanks for the quick answer which led me to find the solution. 
It's funny though because it seems to be the other way around. Now that I have chosen BibTex there seems to be no problem reading the `@document` type. BibLaTex on the other hand does not seem to know this type. 
Thanks a lot! You saved my day!

**Comment by crsh** [comment]
Hah, thanks for letting me konw. Glad I could help!
